### PR TITLE
Multi OS build

### PR DESCRIPTION
**Pull request by SimonBiggs**
@ListIndexOutOfRange,

Over here I have added in a CI that creates a zip file for each of the major OSes that contains everything needed to run the application :slightly_smiling_face:

Let me know if you think this would be enough for people to happily get started

### CODE REVIEW

**Comment by SimonBiggs** [comment]
The artifact downloads are available by going to Actions

image

Then clicking on a complete build

image

Then scrolling down to the bottom where it says "Artifacts"

image

And click on one of them to download it :slightly_smiling_face:

**Comment by ListIndexOutOfRange** [comment]
I couldn't have wished for anything better, you're the man ! 

Should we keep the Electron part in another branch or just remove it ?

**Comment by SimonBiggs** [comment]
> Should we keep the Electron part in another branch or just remove it ?

Given streamlit is a Python library it is my suspicion that using JavaScript tooling may put this out of reach of some Python developers. Potentially leaving it as Python only for the minimal example is the way to go?

What do you think?

**Comment by SimonBiggs** [comment]
Is there anything else that you think we should change?

**Comment by ListIndexOutOfRange** [comment]
Yeah ok you're right. 
I didn't do anything haha but well thank you for your work !
 
 > Is there anything else that you think we should change?

I think it's fine for now. Perhaps we could add some kind of tutorial / explanation and add docstrings and stuffs, but all that can be done later, and doesn't require major changes, so I guess we're good to go !

**Comment by SimonBiggs** [comment]
> Perhaps we could add some kind of tutorial / explanation

Might you want to put something like that together?

**Comment by ListIndexOutOfRange** [comment]
Sure, I'll do it. Not today if it's ok for you, I got other stuffs to work on, but within the week for sure. 
Btw I feel like poetry isn't widely used (yet) and may confuse some Python dev, so maybe it would be good to add some words on it in the tuto, what do you think ?

**Comment by SimonBiggs** [comment]
> Not today if it's ok for you

Completely okay.

> Btw I feel like poetry isn't widely used (yet) and may confuse some Python dev, so maybe it would be good to add some words on it in the tuto, what do you think ?

Sure, go for it :).

**Pull request merged**
